- name: Create temporary folder for sql schema
  ansible.builtin.tempfile:
    state: directory
  register: temp_folder

- name: Copy superlinks schema
  ansible.builtin.copy:
    src: ../sql/superlinks.schema.sql
    dest: '{{ temp_folder.path }}'

- name: Create Superlinks database
  community.mysql.mysql_db:
    name:
    - superlinks
    login_unix_socket: /var/run/mysqld/mysqld.sock
    login_user: root
    state: present
  become: true
  register: new_database

- name: Import superlinks db schema
  community.mysql.mysql_db:
    name: superlinks
    login_unix_socket: /var/run/mysqld/mysqld.sock
    login_user: root
    state: import
    target: '{{ temp_folder.path }}/superlinks.schema.sql'
  become: true
  when: new_database is changed

- name: Delete temporary folder
  ansible.builtin.file:
    path: '{{ temp_folder.path }}'
    state: absent

- name: Generate random passwords for DB users
  ansible.builtin.set_fact:
    password_authenticated: "{{ lookup('community.general.random_string', length=40) }}"
    password_public: "{{ lookup('community.general.random_string', length=40) }}"

- name: Create authenticated DB user
  community.mysql.mysql_user:
    login_unix_socket: /var/run/mysqld/mysqld.sock
    login_user: root
    name: superlinks
    password: '{{ password_authenticated }}'
    priv:
      'superlinks.*': 'SELECT,INSERT,UPDATE,DELETE'
    state: present
  become: true

- name: Create public DB user
  community.mysql.mysql_user:
    login_unix_socket: /var/run/mysqld/mysqld.sock
    login_user: root
    name: superlinks-public
    password: '{{ password_public }}'
    priv:
      'superlinks.view_public': 'SELECT'
    state: present
  become: true
